name: Deploy to GitHub pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8

      - name: Publish .NET Project
        run: dotnet publish ./WebShowcase/WebShowcase.csproj -c Release -o release --nologo
    
      - name: Change base-tag in index.html
        run: sed -i 's/<base href="\/" \/>/<base href="\/PGAL\/" \/>/g' release/wwwroot/index.html
    
      - name: Fix service-worker-assets.js hashes
        working-directory: release/wwwroot
        run: |
          jsFile=$(<service-worker-assets.js)
          json=$(echo "$jsFile" | sed "s/self.assetsManifest = //g" | sed "s/;//g")
          assets=$(echo "$json" | jq '.assets[]' -c)
          for asset in $assets
          do
            oldHash=$(echo "$asset" | jq '.hash')
            oldHash="${oldHash:1:-1}"
            path=$(echo "$asset" | jq '.url')
            path="${path:1:-1}"
            newHash="sha256-$(openssl dgst -sha256 -binary $path | openssl base64 -A)"
        
            if [ $oldHash != $newHash ]; then
              oldHash=$(echo "$oldHash" | sed 's;/;\\/;g')
              newHash=$(echo "$newHash" | sed 's;/;\\/;g')
              echo "Updating hash for $path from $oldHash to $newHash"
              oldHash=$(echo "$oldHash" | sed 's;/;\\/;g')
              jsFile=$(echo -n "$jsFile" | sed "s;$oldHash;$newHash;g")
            fi
          done
        
          echo -n "$jsFile" > service-worker-assets.js
    
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
