name: Deploy to GitHub pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.100-preview.4.25258.110

      - name: Setup WASM workload
        run: dotnet workload restore ./WebShowcase/WebShowcase.csproj

      - name: Setup NPM dependencies
        run: |
          cd ./WebShowcase
          npm install
          cd ..

      - name: Publish .NET Project
        run: dotnet publish ./WebShowcase/WebShowcase.csproj -c Release -o release --nologo
    
      - name: Change base-tag in index.html
        run: sed -i 's/<base href="\/" \/>/<base href="\/PGAL\/" \/>/g' release/wwwroot/index.html
    
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
